// --- Day 8: Resonant Collinearity ---

//frequency -- lowercase letter, uppercase letter, or digit. Map of antennas:

// ............
// ........0...
// .....0......
// .......0....
// ....0.......
// ......A.....
// ............
// ............
// ........A...
// .........A..
// ............
// ............

// an antinode occurs at any point that is perfectly in line with two antennas of the same frequency - but only when one of the antennas is twice as far away as the other. This means that for any pair of antennas with the same frequency, there are two antinodes, one on either side of them.

// So, for these two antennas with frequency a, they create the two antinodes marked with #:

// ..........
// ...#......
// ..........
// ....a.....
// ..........
// .....a....
// ..........
// ......#...
// ..........
// ..........

// Adding a third antenna with the same frequency creates several more antinodes. It would ideally add four antinodes, but two are off the right side of the map, so instead it adds only two:

// ..........
// ...#......
// #.........
// ....a.....
// ........a.
// .....a....
// ..#.......
// ......#...
// ..........
// ..........

// Antennas with different frequencies don't create antinodes; A and a count as different frequencies. However, antinodes can occur at locations that contain antennas. In this diagram, the lone antenna with frequency capital A creates no antinodes but has a lowercase-a-frequency antinode at its location:

// ..........
// ...#......
// #.........
// ....a.....
// ........a.
// .....a....
// ..#.......
// ......A...
// ..........
// ..........

// The first example has antennas with two different frequencies, so the antinodes they create look like this, plus an antinode overlapping the topmost A-frequency antenna:

// ......#....#
// ...#....0...
// ....#0....#.
// ..#....0....
// ....0....#..
// .#....A.....
// ...#........
// #......#....
// ........A...
// .........A..
// ..........#.
// ..........#.

// Because the topmost A-frequency antenna overlaps with a 0-frequency antinode, there are 14 total unique locations that contain an antinode within the bounds of the map.

// Calculate the impact of the signal. How many unique locations within the bounds of the map contain an antinode?
mod utils;
use utils:: {errors, parser, antinode_checker};
use crate::utils::errors::AntiNodeError;

fn main() -> Result<(), AntiNodeError> {
    let input = parser::parse_input("src/input/input.txt")?;
    let grid_dimensions = parser::find_grid_dimensions("src/input/input.txt")?;
    println!("{:?}", input);
    println!("{:?}", grid_dimensions);
    let antinodes = antinode_checker::antinode(input, grid_dimensions)?;
    println!("{:?}", antinodes);
    Ok(())

}
